/**
 * Locale Layout
 *
 * Wraps all pages under a specific locale (e.g., /en) with the
 * NextIntlClientProvider so client components can access translations.
 *
 * Key responsibilities:
 *   - Validates the locale from the URL segment against supported locales
 *   - Sets the request locale for server-side translations
 *   - Wraps children in NextIntlClientProvider for client-side translations
 *   - Generates static params for all supported locales (SSG)
 *
 * Note: <html> and <body> tags live in the root layout (app/layout.tsx).
 * This layout adds the i18n provider and React Query provider layers.
 */
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages, setRequestLocale } from 'next-intl/server'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { QueryProvider } from '@/components/providers/query-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Pre-render all locale variants at build time
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params

  // Return 404 if the locale is not in the supported list
  if (!routing.locales.includes(locale as (typeof routing.locales)[number])) {
    notFound()
  }

  // Enable static rendering for this locale
  setRequestLocale(locale)

  // Load translation messages for the current locale
  const messages = await getMessages()

  return (
    // Provides translations to all client components via useTranslations()
    <NextIntlClientProvider messages={messages}>
      {/* Provides React Query to all client components via useQuery/useMutation */}
      <QueryProvider>
        {children}
      </QueryProvider>
    </NextIntlClientProvider>
  )
}
