/**
 * Locale Layout
 *
 * The main layout that wraps all pages under a specific locale (e.g., /en).
 * This is where the <html> lang attribute, fonts, and global providers live.
 *
 * Key responsibilities:
 *   - Validates the locale from the URL segment against supported locales
 *   - Sets the request locale for server-side translations
 *   - Wraps the app in NextIntlClientProvider for client-side translations
 *   - Generates static params for all supported locales (SSG)
 */
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages, setRequestLocale } from 'next-intl/server'
import { notFound } from 'next/navigation'
import { Geist, Geist_Mono, Inter } from 'next/font/google'
import { routing } from '@/i18n/routing'
import '../globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Pre-render all locale variants at build time
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params

  // Return 404 if the locale is not in the supported list
  if (!routing.locales.includes(locale as (typeof routing.locales)[number])) {
    notFound()
  }

  // Enable static rendering for this locale
  setRequestLocale(locale)

  // Load translation messages for the current locale
  const messages = await getMessages()

  return (
    <html lang={locale} className={inter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Provides translations to all client components via useTranslations() */}
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
